services:
  database:
    container_name: salestack_db
    image: postgres:15-bullseye
    ports:
    - 5432:5432
    environment:
        - POSTGRES_USER=jradmin
        - POSTGRES_PASSWORD=12345678
        - POSTGRES_DB=SalestackDb

    volumes:
        - db_vol:/var/lib/postgresql/pg_data

  salestack:
    container_name: salestack_api
    image: ${DOCKER_REGISTRY-}salestack
    build:
        context: .
        dockerfile: Salestack/Dockerfile
    ports:
      - 5000:5000
      - 5001:5001

    develop:
      watch:
        - path: ./
          action: rebuild

volumes:
  db_vol: