services:
  salestack:
    container_name: salestack_api
    image: ${DOCKER_REGISTRY-}salestack
    build:
      context: .
      dockerfile: Salestack/Dockerfile
    ports:
      - 5000:5000
      - 5001:5001